// Tipos de activo
export const TIPO_ACTIVO = {
  PATENTE: 'PATENTE',
  REQUERIMIENTO_EMPRESARIAL: 'REQUERIMIENTO_EMPRESARIAL'
}

// Estados de proceso
export const ESTADO_PROCESO = {
  ACTIVO: 'ACTIVO',
  PAUSADO: 'PAUSADO',
  FINALIZADO: 'FINALIZADO',
  CANCELADO: 'CANCELADO',
  ARCHIVADO: 'ARCHIVADO'
}

// Fases de vinculación
export const FASE_VINCULACION = {
  CARACTERIZACION: 'CARACTERIZACION',
  ENRIQUECIMIENTO: 'ENRIQUECIMIENTO',
  MATCH: 'MATCH',
  ESCALAMIENTO: 'ESCALAMIENTO',
  TRANSFERENCIA: 'TRANSFERENCIA',
  FORMULACION_RETO: 'FORMULACION_RETO',
  CONVOCATORIA: 'CONVOCATORIA',
  POSTULACION: 'POSTULACION',
  SELECCION: 'SELECCION',
  ANTEPROYECTO: 'ANTEPROYECTO',
  EJECUCION: 'EJECUCION',
  CIERRE: 'CIERRE'
}

// Flujos de fases por tipo
export const FLUJOS_FASES = {
  [TIPO_ACTIVO.PATENTE]: [
    FASE_VINCULACION.CARACTERIZACION,
    FASE_VINCULACION.ENRIQUECIMIENTO,
    FASE_VINCULACION.MATCH,
    FASE_VINCULACION.ESCALAMIENTO,
    FASE_VINCULACION.TRANSFERENCIA
  ],
  [TIPO_ACTIVO.REQUERIMIENTO_EMPRESARIAL]: [
    FASE_VINCULACION.FORMULACION_RETO,
    FASE_VINCULACION.CONVOCATORIA,
    FASE_VINCULACION.POSTULACION,
    FASE_VINCULACION.SELECCION,
    FASE_VINCULACION.ANTEPROYECTO,
    FASE_VINCULACION.EJECUCION,
    FASE_VINCULACION.CIERRE
  ]
}

// Estados de actividad
export const ESTADO_ACTIVIDAD = {
  CREADA: 'CREADA',
  EN_PROGRESO: 'EN_PROGRESO',
  EN_REVISION: 'EN_REVISION',
  OBSERVADA: 'OBSERVADA',
  LISTA_PARA_CIERRE: 'LISTA_PARA_CIERRE',
  APROBADA: 'APROBADA',
  RECHAZADA: 'RECHAZADA'
}

// Máquina de estados de actividad
export const TRANSICIONES_ACTIVIDAD = {
  [ESTADO_ACTIVIDAD.CREADA]: [ESTADO_ACTIVIDAD.EN_PROGRESO],
  [ESTADO_ACTIVIDAD.EN_PROGRESO]: [ESTADO_ACTIVIDAD.EN_REVISION, ESTADO_ACTIVIDAD.OBSERVADA],
  [ESTADO_ACTIVIDAD.EN_REVISION]: [ESTADO_ACTIVIDAD.LISTA_PARA_CIERRE, ESTADO_ACTIVIDAD.OBSERVADA],
  [ESTADO_ACTIVIDAD.LISTA_PARA_CIERRE]: [ESTADO_ACTIVIDAD.OBSERVADA],
  [ESTADO_ACTIVIDAD.OBSERVADA]: [ESTADO_ACTIVIDAD.EN_PROGRESO, ESTADO_ACTIVIDAD.EN_REVISION],
  [ESTADO_ACTIVIDAD.APROBADA]: []
}

// Tipos de actividad
export const TIPO_ACTIVIDAD = {
  DOCUMENTO: 'DOCUMENTO',
  REUNION: 'REUNION',
  TAREA: 'TAREA',
  REVISION: 'REVISION',
  OTRO: 'OTRO'
}

// Estados de evidencia
export const ESTADO_EVIDENCIA = {
  PENDIENTE: 'PENDIENTE',
  APROBADA: 'APROBADA',
  RECHAZADA: 'RECHAZADA'
}

// ✅ Roles de sistema — exactamente los que existen en el seed (AmbitoRol = SISTEMA)
// Eliminados: RESPONSABLE_FASE, EVALUADOR, REVISOR, EMPRESA (no están en el seed)
export const ROL_SISTEMA = {
  ADMIN_SISTEMA:      'ADMIN_SISTEMA',
  GESTOR_VINCULACION: 'GESTOR_VINCULACION',
  INVESTIGADOR:       'INVESTIGADOR',
  OBSERVADOR:         'OBSERVADOR',
}

// Roles en proceso (AmbitoRol = PROCESO en el seed)
export const ROL_PROCESO = {
  RESPONSABLE_PROCESO: 'RESPONSABLE_PROCESO',
  APOYO:               'APOYO',
  OBSERVADOR_PROCESO:  'OBSERVADOR_PROCESO', // ← era 'OBSERVADOR' en el constants viejo
}

// Roles en actividad (AmbitoRol = ACTIVIDAD en el seed)
// ✅ Códigos correctos del seed — eran RESPONSABLE/REVISOR/PARTICIPANTE en el constants viejo
export const ROL_ACTIVIDAD = {
  RESPONSABLE_TAREA:  'RESPONSABLE_TAREA',
  REVISOR_TAREA:      'REVISOR_TAREA',
  PARTICIPANTE_TAREA: 'PARTICIPANTE_TAREA',
}

// Roles de empresa (AmbitoRol = EMPRESA en el seed / enum RolEmpresa)
export const ROL_EMPRESA = {
  INTERESADA:   'INTERESADA',
  ALIADA:       'ALIADA',
  FINANCIADORA: 'FINANCIADORA',
}

// Tipos de decisión
export const DECISION_TIPO = {
  CONTINUAR:              'CONTINUAR',
  RETROCEDER:             'RETROCEDER',
  PAUSAR:                 'PAUSAR',
  CANCELAR:               'CANCELAR',
  FINALIZAR:              'FINALIZAR',
  RELANZAR_CONVOCATORIA:  'RELANZAR_CONVOCATORIA'
}

// Rangos TRL por fase
export const TRL_RANGES = {
  [FASE_VINCULACION.CARACTERIZACION]: { min: 1, max: 3 },
  [FASE_VINCULACION.ENRIQUECIMIENTO]: { min: 3, max: 5 },
  [FASE_VINCULACION.MATCH]:           { min: 4, max: 6 },
  [FASE_VINCULACION.ESCALAMIENTO]:    { min: 6, max: 8 },
  [FASE_VINCULACION.TRANSFERENCIA]:   { min: 7, max: 9 }
}

// Colores por estado
export const ESTADO_COLORS = {
  [ESTADO_PROCESO.ACTIVO]:     'green',
  [ESTADO_PROCESO.PAUSADO]:    'yellow',
  [ESTADO_PROCESO.FINALIZADO]: 'blue',
  [ESTADO_PROCESO.CANCELADO]:  'red',
  [ESTADO_PROCESO.ARCHIVADO]:  'gray',

  [ESTADO_ACTIVIDAD.CREADA]:           'gray',
  [ESTADO_ACTIVIDAD.EN_PROGRESO]:      'blue',
  [ESTADO_ACTIVIDAD.EN_REVISION]:      'yellow',
  [ESTADO_ACTIVIDAD.OBSERVADA]:        'orange',
  [ESTADO_ACTIVIDAD.LISTA_PARA_CIERRE]:'purple',
  [ESTADO_ACTIVIDAD.APROBADA]:         'green',

  [ESTADO_EVIDENCIA.PENDIENTE]: 'yellow',
  [ESTADO_EVIDENCIA.APROBADA]:  'green',
  [ESTADO_EVIDENCIA.RECHAZADA]: 'red'
}